name: Bug汇报
description: 汇报一个BUG
labels: ["bug", "evaluation required"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此Bug报告！
        为了方便进行Bug定位，我们需要知道如何重现该Bug。
  - type: textarea
    id: bug-explanation
    attributes:
      label: 错误说明
      description: |
        - 告诉我们问题出在哪里。
        - 解释重现错误的不同步骤。
        - 有必要的话可以提供一个最小且可重现的示例。

        您可以附上一些屏幕截图或/和视频以更好地说明问题。
      placeholder: 在此键入...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 版本
      description: 您运行的是哪个版本？
      placeholder: "示例: 1.0.0"
    validations:
      required: true
