blank_issues_enabled: false
contact_links:
  - name: Github 讨论组
    url: https://github.com/xqyjlj/csp/discussions
    about: 一些使用问题请到 Discussion 提问。

  - name: csp 主页导航
    url: https://xqyjlj.github.io/2022/08/20/CSP%E4%B8%BB%E9%A1%B5%E5%AF%BC%E8%88%AA/
    about: 有关 csp 的简介与部分使用教程

  - name: QQ 群
    url: https://jq.qq.com/?_wv=1027&k=CWt7TZln
    about: "群号 444093737"
