# .github/workflows/push_and_pr.yml

name: push and pull_request verification
on: [push, pull_request]

env:
  solution: csp.sln
  buildConfiguration: Release

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: xqyjlj/csp_mcu_db
          path: Apps/CSP.Apps.Dev/bin/${{ env.buildConfiguration }}/net6.0-windows/Database/MCU

      - uses: actions/checkout@v3
        with:
          repository: xqyjlj/csp_hal_apm32f1
          path: Apps/CSP.Apps.Dev/bin/${{ env.buildConfiguration }}/net6.0-windows/Repository/csp_hal_apm32f1-latest

      - name: build_and_test
        uses: ./.github/actions/build_and_test
        timeout-minutes: 20
        with:
          solution: ${{ env.solution }}
          buildConfiguration: ${{ env.buildConfiguration }}
